##
## EPITECH PROJECT, 2020
## lib
## File description:
## make
##

all:
	make -C linked_list/
	make -C math/
	make -C mem/
	make -C printf/
	make -C str/
	make -C tab/

debug:
	make -C linked_list/ debug
	make -C math/ debug
	make -C mem/ debug
	make -C printf/ debug
	make -C str/ debug
	make -C tab/ debug

clean:
	make -C linked_list/ clean
	make -C math/ clean
	make -C mem/ clean
	make -C printf/ clean
	make -C str/ clean
	make -C tab/ clean

fclean:
	make -C linked_list/ fclean
	make -C math/ fclean
	make -C mem/ fclean
	make -C printf/ fclean
	make -C str/ fclean
	make -C tab/ fclean

re:	fclean all

.PHONY: all debug clean fclean re