name: C Lib Unit Tests

on: [push]

defaults:
  run:
    shell: bash
    working-directory: c-lib


jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Criterion and Gcovr
      run: |
        sudo add-apt-repository ppa:snaipewastaken/ppa
        sudo apt-get update
        sudo apt-get install criterion-dev gcovr
    - name: Build
      run: make tests_run
    - name: Run
      run: ./unit_test -j1 --verbose
